services:
  nginx:
    image: nginx:latest
    container_name: browserquest-nginx
    ports:
      - "8084:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - backend1
      - backend2
      - backend3
      - frontend
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"
    networks:
      - browserquest-network
    restart: unless-stopped

  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browserquest-backend1
    ports:
      - "8001:8000"
    volumes:
      - ./shared:/app/shared
    environment:
      - CONFIG_PATH=./server/config1.json
    networks:
      - browserquest-network
    restart: unless-stopped

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browserquest-backend2
    ports:
      - "8002:8000"
    volumes:
      - ./shared:/app/shared
    environment:
      - CONFIG_PATH=./server/config1.json
    networks:
      - browserquest-network
    restart: unless-stopped

  backend3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: browserquest-backend3
    ports:
      - "8003:8000"
    volumes:
      - ./shared:/app/shared
    environment:
      - CONFIG_PATH=./server/config1.json
    networks:
      - browserquest-network
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: browserquest-frontend
    ports:
      - "3000:3000"
    networks:
      - browserquest-network
    restart: unless-stopped

networks:
  browserquest-network:
    driver: bridge